'use strict';

exports.ARROW = 'ARROW';

exports.CLASS = 'CLASS';

exports.OBJECT_LITERALS = 'OBJECT_LITERALS';

exports.TEMPLATE_LITERALS = 'TEMPLATE_LITERALS';

exports.DESTRUCTURING = 'DESTRUCTURING';

exports.DEFAULT_PARAMETERS = 'DEFAULT_PARAMETERS';

exports.REST_PARAMETERS = 'REST_PARAMETERS';

exports.SPREAD_OPERATOR = 'SPREAD_OPERATOR';

exports.LET = 'LET';

exports.CONST = 'CONST';

exports.ITERATORS_FOR_OF = 'ITERATORS_FOR_OF';

exports.GENERATORS = 'GENERATORS';

exports.MODULES = 'MODULES';

exports.MODULE_LOADERS = 'MODULE_LOADERS';

exports.OBJECT_SUPER = 'OBJECT_SUPER';

exports.BINARY_OCTAL_LITERALS = 'BINARY_OCTAL_LITERALS';

exports.UNICODE_REGEX = 'UNICODE_REGEX';

exports.STICKY_REGEX = 'STICKY_REGEX';

exports.UNICODE_STRING_LITERALS = 'UNICODE_STRING_LITERALS';

exports.TYPEOF_SYMBOL = 'TYPEOF_SYMBOL';

exports.FUNCTION_NAME = 'FUNCTION_NAME';

exports.BLOCK_LEVEL_FUNCTION = 'BLOCK_LEVEL_FUNCTION';