'use strict';

exports.CLASS_PROPERTIES = 'CLASS_PROPERTIES';

exports.DECORATOR = 'DECORATOR';

exports.OBJECT_REST_SPREAD = 'OBJECT_REST_SPREAD';

exports.DO_EXPRESSION = 'DO_EXPRESSION';

exports.FUNCTION_DOUBLE_COLON_BIND = 'FUNCTION_DOUBLE_COLON_BIND';

exports.ASYNC_FUNCTION_TO_BLUEBIRD = 'ASYNC_FUNCTION_TO_BLUEBIRD';

exports.CALLABLE_CLASS_CONSTRUCTOR = 'CALLABLE_CLASS_CONSTRUCTOR';
exports.EXPORT_EXTENSIONS = 'EXPORT_EXTENSIONS';